[package]
name = "hose-primitives"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
pallas = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = "0.4.39"
